server {
    listen 80;

    location / {
        proxy_set_header Host $host;       # Pass original Host header
        proxy_set_header X-Real-IP $remote_addr; # Pass client IP address
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Pass X-Forwarded-For header
        proxy_set_header X-Forwarded-Proto $scheme; # Pass X-Forwarded-Proto header

         proxy_pass http://node-app:4000; # Forward requests to the backend server to My Continer
         proxy_redirect off; # Disable automatic redirects
    }
}

